---
- name: Install vagrant
  hosts: all
  gather_facts: True
  tags: vm,vagrant
  tasks:
    - name: Download and add HashiCorp GPG key to keyring
      become: true
      shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp.gpg
      args:
        creates: /etc/apt/keyrings/hashicorp.gpg
    - name: Add vagrant apt repository
      become: true
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/hashicorp.gpg arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
        filename: hashicorp
    - name: Install vagrant
      become: true
      apt:
        name: vagrant
