---
- name: Install sublime-text
  hosts: all
  gather_facts: False
  tags: graphical,media,sublime-text
  tasks:
    - name: Install sublime-text
      become: true
      community.general.snap:
        name: sublime-text
        classic: true
