---
- name: Install python3
  hosts: all
  gather_facts: False
  tags: python,python3
  tasks:
    - name: Install python3
      become: true
      apt:
        name: python3
    - name: Install python3-pip
      become: true
      apt:
        name: python3-pip
