---
- name: Install zsh
  hosts: all
  tasks:
    - name: Install zsh
      become: true
      apt:
        state: present
        name: zsh
    - name: Make zsh default shell
      become: true
      shell: USER=$(whoami) sudo chsh -s $(which zsh) $USER
      args:
        executable: /bin/bash
