---
- name: Install docker registry
  hosts: all
  gather_facts: False
  tags: docker,docker-registry
  tasks:
    - name: Start docker registry
      become: true
      docker_container:
        name: registry
        image: registry:2
        published_ports:
          - "5000:5000"
        state: started
        restart_policy: unless-stopped
