---
- name: Install docker
  hosts: all
  tags: docker
  tasks:
    - name: Install docker
      become: true
      apt:
        state: present
        name: docker.io
    - name: Install dockerx plugin
      become: true
      apt:
        state: present
        name: docker-buildx
    - name: Add docker group
      become: true
      group:
        name: docker
        state: present
    - name: Add current user to docker group so 'sudo' is not needed for every docker command
      become: true
      user:
        name: "{{ansible_env.USER}}"
        groups: docker
        append: true
    - name: Install docker-compose-v2
      become: true
      apt:
        state: present
        name: docker-compose-v2
