---
- name: Install lazydocker
  hosts: all
  tasks:
    - name: Download lazydocker install script
      get_url:
        url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
        dest: /tmp/install_lazydocker.sh
        mode: 0700
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Store current version
      shell:
          cmd: lazydocker --version
      ignore_errors: true
      register: current_version
      changed_when: false
    - name: Install lazydocker
      shell: /tmp/install_lazydocker.sh
      become: true
      environment:
        DIR: /usr/local/bin
      args:
        executable: /bin/sh
      changed_when: false
    - name: Report as changed when new version installed
      shell:
          cmd: lazydocker --version
      register: new_version
      changed_when: current_version.stdout != new_version.stdout
