---
- name: Install lazydocker
  hosts: all
  tasks:
    - name: Download lazydocker install script
      get_url:
        url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
        dest: /tmp/install_lazydocker.sh
        mode: 0700
        timeout: 30
    - name: Install lazydocker
      shell: /tmp/install_lazydocker.sh
      become: true
      environment:
        DIR: /usr/local/bin
      args:
        executable: /bin/sh
