---
- name: Configure git
  hosts: all
  tasks:
    - name: Make sure global gitignore file is present
      file:
        path: ~/.gitignore_global
        state: touch
        mode: 0700
        access_time: preserve
        modification_time: preserve
    - name: Fill global .gitignore file
      lineinfile:
        path: ~/.gitignore_global
        state: present
        line: '{{ item }}'
      loop:
        - '*.iml'
        - '.idea/'
        - '*.hprof'
        - '.DS_Store'
        - '.vscode'
        - 'composer.lock'
        - 'packages.lock'
    - name: Configure git to use global .gitignore file
      git_config:
        name: core.excludesfile
        scope: global
        value: '{{ ansible_env.HOME }}/.gitignore_global'
    - name: Change default comment character to ';' in git
      git_config:
        name: core.commentChar
        scope: global
        value: ';'
