---
- name: Install lazygit
  hosts: all
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
        return_content: yes
      register: lazygit_latest_version_metadata
      until: lazygit_latest_version_metadata is success
      retries: 3
      delay: 5
    - name: Parse latest version tag
      set_fact:
        lazygit_latest_version: "{{ lazygit_latest_version_metadata.json.tag_name | regex_replace('^v', '') }}"
    - name: Download lazygit
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_latest_version }}_Linux_x86_64.tar.gz"
        dest: /tmp/lazygit.tar.gz
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Remove temp binary if present
      file:
        path: /tmp/lazygit
        state: absent
      changed_when: false
    - name: Unpack lazygit
      unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /tmp
        remote_src: yes
      changed_when: false
    - name: Store md5sum of current binary
      shell:
        cmd: md5sum /usr/local/bin/lazygit | awk '{print $1}'
      register: current_md5sum
      changed_when: false
    - name: Store md5sum of new binary
      shell:
        cmd: md5sum /tmp/lazygit | awk '{print $1}'
      register: new_md5sum
      changed_when: false
    - name: Move lazygit to /usr/local/bin
      when: current_md5sum.stdout != new_md5sum.stdout
      become: true
      shell: mv /tmp/lazygit /usr/local/bin/lazygit
    - name: Make lazygit executable
      file:
        path: /usr/local/bin/lazygit
        mode: 0700
