---
- name: Install lazygit
  hosts: all
  gather_facts: False
  tags: git,lazygit
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
        return_content: yes
      register: lazygit_latest_version_metadata
      until: lazygit_latest_version_metadata is success
      retries: 3
      delay: 5
    - name: Parse latest version tag
      set_fact:
        lazygit_latest_version: "{{ lazygit_latest_version_metadata.json.tag_name | regex_replace('^v', '') }}"
    - name: Download lazygit {{ lazygit_latest_version }}
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_latest_version }}_Linux_x86_64.tar.gz"
        dest: /tmp/lazygit.tar.gz
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Unpack lazygit
      unarchive:
        src: /tmp/lazygit.tar.gz
        dest: /tmp
        remote_src: yes
      changed_when: false
    - name: Copy lazygit binary
      become: true
      copy:
        src: /tmp/lazygit
        dest: /usr/local/bin/lazygit
        mode: 0700
