- name: Install flatpak
  become: true
  apt:
    state: present
    name: flatpak
- name: Add flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
- name: Update all packages
  shell: "flatpak update -y"
  register: output
  changed_when: "'Nothing to do.' not in output.stdout"
