---
- name: Install cheat
  hosts: all
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/cheat/cheat/releases/latest
        return_content: yes
      register: cheat_latest_version_metadata
      until: cheat_latest_version_metadata is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Parse latest version tag
      set_fact:
        cheat_latest_version: "{{ cheat_latest_version_metadata.json.tag_name }}"
    - name: Download cheat
      get_url:
        url: "https://github.com/cheat/cheat/releases/download/{{ cheat_latest_version }}/cheat-linux-amd64.gz"
        dest: /tmp/cheat.gz
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Unpack cheat
      shell:
        cmd: gunzip /tmp/cheat.gz
        chdir: /tmp
      changed_when: false
    - name: Move cheat to /usr/local/bin
      become: true
      shell: mv /tmp/cheat /usr/local/bin/cheat
    - name: Make cheat executable
      file:
        path: /usr/local/bin/cheat
        mode: 0700
