---
- name: Install cheat
  hosts: all
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/cheat/cheat/releases/latest
        return_content: yes
      register: cheat_latest_version_metadata
    - name: Parse latest version tag
      set_fact:
          cheat_latest_version: "{{ cheat_latest_version_metadata.json.tag_name }}"
    - name: Download cheat
      get_url:
        url: "https://github.com/cheat/cheat/releases/download/{{ cheat_latest_version }}/cheat-linux-amd64.gz"
        dest: /tmp/cheat.gz
        timeout: 30
    - name: Unpack cheat
      shell: gunzip /tmp/cheat.gz
    - name: Make cheat executable
      file:
        path: /tmp/cheat
        mode: 0700
    - name: Move cheat to /usr/local/bin
      become: true
      shell: mv /tmp/cheat /usr/local/bin/cheat
