---
- name: Install signal
  hosts: all
  gather_facts: False
  tags: graphical,communicator,signal
  tasks:
    - name: Install signal
      become: true
      community.general.snap:
        name: signal-desktop
