- name: Install brave
  become: true
  community.general.snap:
    name: brave
- name: Install librewolf
  community.general.flatpak:
    name: io.gitlab.librewolf-community
    state: present
    remote: flathub
    method: user
- name: Install mullvad
  become: true
  community.general.snap:
    name: mullvad-browser
- name: Install tor
  become: true
  apt:
    name: torbrowser-launcher
