---
- name: Install niri and Dank Material Shell
  hosts: all
  gather_facts: False
  tags: window-manager,niri,dms
  tasks:
    - name: Add Dank Linux PPA
      become: true
      command: add-apt-repository --yes ppa:avengemedia/danklinux
      register: danklinux_ppa
      changed_when: "'already exists' not in danklinux_ppa.stdout"
    - name: Add DMS PPA
      become: true
      command: add-apt-repository --yes ppa:avengemedia/dms
      register: dms_ppa
      changed_when: "'already exists' not in dms_ppa.stdout"
    - name: Install niri and dms
      become: true
      apt:
        state: present
        name:
          - niri
          - dms
