---
- name: Install mvnvm
  hosts: all
  gather_facts: False
  tags: java,mvnvm
  tasks:
    - name: Download binary
      get_url:
        url: https://bitbucket.org/mjensen/mvnvm/raw/master/mvn
        dest: /tmp/mvn
        mode: 0700
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Copy mvn to /usr/local/bin
      become: true
      copy:
          src: /tmp/mvn
          dest: /usr/local/bin/mvn
          mode: 0777
