---
- name: Install visual-vm
  hosts: all
  gather_facts: False
  tags: java,visual-vm
  tasks:
    - name: Install visual-vm
      become: true
      tags: graphical,java,visual-vm
      apt:
        state: present
        name: visualvm
