---
- name: Install nvm
  hosts: all
  gather_facts: False
  tags: javascript,nvm
  tasks:
    - name: Download nvm install script
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
        dest: /tmp/nvm.sh
        mode: 0700
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Get current nvm version (if any)
      shell: "cat ~/.nvm/package.json | grep \\\"version\\\":"
      register: pre_update_nvm_version
      changed_when: false
      ignore_errors: true
    - name: Install nvm
      shell: bash /tmp/nvm.sh # instruction specifically says to use bash
      changed_when: false
    - name: Report as changed when new nvm version installed
      shell: "cat ~/.nvm/package.json | grep \\\"version\\\":"
      register: post_update_nvm_version
      changed_when: pre_update_nvm_version.stdout != post_update_nvm_version.stdout
