---
- name: Install cheat
  hosts: all
  gather_facts: False
  tags: knowledge,cheat
  tasks:
    - name: Download latest release metadata
      uri:
        timeout: 30
        url: https://api.github.com/repos/cheat/cheat/releases/latest
        return_content: yes
      register: cheat_latest_version_metadata
      until: cheat_latest_version_metadata is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Parse latest version tag
      set_fact:
        cheat_latest_version: "{{ cheat_latest_version_metadata.json.tag_name }}"
    - name: Download cheat {{ cheat_latest_version }}
      get_url:
        url: "https://github.com/cheat/cheat/releases/download/{{ cheat_latest_version }}/cheat-linux-amd64.gz"
        dest: /tmp/cheat.gz
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Remove temp binary if present
      file:
        path: /tmp/cheat
        state: absent
      changed_when: false
    - name: Unpack cheat
      shell:
        cmd: gunzip /tmp/cheat.gz
        chdir: /tmp
      changed_when: false
    - name: Copy cheat to /usr/local/bin
      become: true
      copy:
        src: /tmp/cheat
        dest: /usr/local/bin/cheat
        mode: 0700
