---
- name: Install apt packages
  hosts: all
  gather_facts: False
  tags: apt
  tasks:
    - name: Install apt packages
      become: true
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - baobab # disc analyzer
        - filezilla
        - flameshot
        - gimp
        - gnome-disk-utility
        - graphviz # needed for intellij plugin plantUML
        - keepassxc
        - wine
        - xclip
