---
- name: Install apt and snap packages
  hosts: all
  tasks:
    - name: Remove packages
      become: true
      apt:
        state: absent
        name: '{{ item }}'
      loop:
        - curl # snap has never version
        - unattented-upgrades # to have bigger control when upgrades are run
    - name: Install apt packages
      become: true
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - bat
        - firefox
        - flameshot
        - gimp
        - graphviz # needed for intellij plugin plantUML
        - hexyl # hex viewer https://github.com/sharkdp/hexyl
        - kwin-bismuth # tiling window management script for kde
        - mc
        - nmap
        - oathtool # 2FA code, e.g. oathtool -b --totp 'secret code' | xclip -sel clip
        - paprefs # to have virtual device capable of streaming via multiple physical devices
        - pipx
        - snap
        - speech-dispatcher # for speaking exit code in terminal of last executed command
        - tmux
        - tmuxinator
        - unrar
        - unzip
        - wine
        - xclip
        - yarn
        - yakuake
        - vagrant
        - virtualbox
    - name: Install snap packages
      become: true
      community.general.snap:
        name: '{{ item.package }}'
        channel: latest/edge
        classic: '{{ item.classic }}'
      loop:
        - { package: authy, classic: false }
        - { package: curl, classic: false }
        - { package: foobar2000, classic: false }
        - { package: intellij-idea-ultimate, classic: true }
        - { package: postman, classic: false }
        - { package: signal-desktop, classic: false }
        - { package: spotify, classic: false }
        - { package: sublime-text, classic: true }
        - { package: yq, classic: false }
