---
- name: Install apt packages
  hosts: all
  gather_facts: False
  tags: apt
  tasks:
    - name: Remove packages
      become: true
      apt:
        state: absent
        name: '{{ item }}'
      loop:
        - unattented-upgrades # to have bigger control when upgrades are run
    - name: Install apt console packages
      become: true
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - snap
    - name: Update all snap packages
      become: true
      command: snap refresh
    - name: Install apt graphical packages
      become: true
      tags: graphical
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - baobab # disc analyzer
        - filezilla
        - flameshot
        - gimp
        - graphviz # needed for intellij plugin plantUML
        - keepassxc
        - wine
        - xclip
