---
- name: Install apt packages
  hosts: all
  gather_facts: False
  tags: apt
  tasks:
    - name: Remove packages
      become: true
      apt:
        state: absent
        name: '{{ item }}'
      loop:
        - unattented-upgrades # to have bigger control when upgrades are run
    - name: Install apt console packages
      become: true
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - bat
        - hexyl # hex viewer https://github.com/sharkdp/hexyl
        - crudini # to manipulate ini files easily
        - fd-find # to find files easily
        - mc
        - nmap
        - oathtool # 2FA code, e.g. oathtool -b --totp 'secret code' | xclip -sel clip
        - paprefs # to have virtual device capable of streaming via multiple physical devices
        - python3
        - python3-pip
        - pipx
        - snap
        - speech-dispatcher # for speaking exit code in terminal of last executed command
        - tmux
        - tmuxinator
        - unrar
        - unzip
        - vagrant
        - virtualbox
        - yarn
        - zbar-tools # to scan QR codes from image or camera
    - name: Install apt graphical packages
      become: true
      tags: graphical
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - baobab # disc analyzer
        - filezilla
        - flameshot
        - gimp
        - graphviz # needed for intellij plugin plantUML
        - keepassxc
        - kwin-bismuth # tiling window management script for kde
        - wine
        - xclip
        - yakuake
