---
- name: Install apt and snap packages
  hosts: all
  tasks:
    - name: Install apt packages
      become: true
      apt:
        state: present
        name: '{{ item }}'
      loop:
        - firefox
        - flameshot
        - gimp
        - graphviz # needed for intellij plugin plantUML
        - mc
        - nmap
        - oathtool # 2FA code, e.g. oathtool -b --totp 'secret code' | xclip -sel clip
        - paprefs # to have virtual device capable of streaming via multiple physical devices
        - snap
        - speech-dispatcher # for speaking exit code in terminal of last executed command
        - tmux
        - tmuxinator
        - unrar
        - unzip
        - wine
        - xclip
        - yarn
    - name: Remove unattended-upgrades to have bigger control when upgrades are run
      become: true
      apt:
        state: absent
        name: unattented-upgrades
    - name: Install snap packages
      become: true
      community.general.snap:
        name: '{{ item.package }}'
        channel: latest/edge
        classic: '{{ item.classic }}'
      loop:
        - { package: postman, classic: false }
        - { package: authy, classic: false }
        - { package: yq, classic: false }
        - { package: foobar2000, classic: false }
        - { package: spotify, classic: false }
        - { package: signal-desktop, classic: false }
        - { package: sublime-text, classic: true }
        - { package: intellij-idea-ultimate, classic: true }
