- name: Keyrings directory
  hosts: all
  become: yes
  tags: keyrings
  tasks:
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
