---
- import_playbook: upgrade-system.yml
- import_playbook: install-packages.yml
- import_playbook: upgrade-python-packages.yml

- import_playbook: git/git.yml
- import_playbook: git/git-global-config.yml
- import_playbook: git/lazygit.yml

- import_playbook: knowledge/cheat.yml
- import_playbook: knowledge/loqseq.yml

- import_playbook: zsh/zsh.yml
- import_playbook: zsh/oh-my-zsh.yml
- import_playbook: zsh/powerlevel10k.yml

- import_playbook: java/jdk.yml
- import_playbook: java/jdk-tools.yml
- import_playbook: java/jenv.yml
- import_playbook: java/jenv-zsh.yml
- import_playbook: java/mvnvm.yml

- import_playbook: docker/docker.yml
- import_playbook: docker/docker-registry.yml
- import_playbook: docker/lazydocker.yml

- import_playbook: javascript/nvm.yml
- import_playbook: javascript/nvm-zsh.yml

- import_playbook: browser/brave.yml
- import_playbook: browser/chromium.yml
- import_playbook: browser/edge.yml
- import_playbook: browser/firefox.yml
- import_playbook: browser/tor.yml

- import_playbook: various/broot.yml
- import_playbook: various/delta.yml
- import_playbook: various/imagemagick.yml
- import_playbook: various/konsave.yml
- import_playbook: various/lsd.yml
- import_playbook: various/mcfly.yml
- import_playbook: various/mcfly-zsh.yml
- import_playbook: various/viddy.yml
- import_playbook: various/zoom.yml
- import_playbook: various/zoxide.yml

- import_playbook: dotfiles/home-dir-as-git-repository.yml

- import_playbook: vim/vim.yml
- import_playbook: vim/vim-plug.yml
- import_playbook: vim/neovim.yml


# TODO
## More tools
# https://github.com/tldr-pages/tldr

# Consider other tools from https://github.com/ibraheemdev/modern-unix
# https://github.com/burntsushi/ripgrep
