---
- name: Upgrade python packages
  hosts: all
  gather_facts: False
  tasks:
    - name: Upgrade outdated packages with pipx
      shell: pipx upgrade-all
      register: result
      changed_when: "'Versions did not change' not in result.stdout"
