- name: Install Brave Browser
  hosts: all
  become: yes
  tags: graphical, brave, browser
  tasks:
    - name: Download Brave GPG key
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'
    - name: Download Brave repository sources file
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
        dest: /etc/apt/sources.list.d/brave-browser-release.sources
        mode: '0644'
    - name: Install Brave browser
      apt:
        name: brave-browser
        state: present
