- name: Install Brave Browser
  hosts: all
  gather_facts: False
  tags: graphical, brave, browser
  tasks:
    - name: Install Brave browser flatpak
      community.general.flatpak:
        name: com.brave.Browser
        state: present
        remote: flathub
        method: user
