---
- name: Install chromium
  hosts: all
  gather_facts: False
  become: true
  tags: graphical, chromium, browser
  tasks:
    - name: Install chromium
      apt:
        state: present
        name: chromium-browser
