---
- name: Install firefox
  hosts: all
  become: true
  tags: graphical, firefox, browser
  tasks:
    - name: Install firefox
      apt:
        name: "firefox"
        state: latest
        update_cache: true
