---
- name: Install mullvad browser
  hosts: all
  gather_facts: False
  tags: graphical,mullvad,browser
  tasks:
    - name: Install mullvad browser
      flatpak:
        name: net.mullvad.MullvadBrowser
        state: present
        method: user
