---
- name: Install ansible
  hosts: all
  tasks:
    - name: Install ansible
      become: true
      apt:
        state: present
        name: ansible
    - name: Install ansible python package
      community.general.pipx:
        name: ansible
    - name: Install ansible-lint python package
      community.general.pipx:
        name: ansible-lint
    - name: Install ansible-review python package
      community.general.pipx:
        name: ansible-review
