---
- name: Install balena for flashing SD cards and USB devices
  hosts: all
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/balena-io/etcher/releases/latest
        return_content: yes
      register: latest_version_metadata
      until: latest_version_metadata is success
      retries: 3
      delay: 5
    - name: Parse latest version tag
      set_fact:
        latest_version: "{{ latest_version_metadata.json.tag_name | regex_replace('^v', '') }}"
    - name: Download balena
      get_url:
        url: "https://github.com/balena-io/etcher/releases/download/v{{ latest_version }}/balena-etcher_{{ latest_version }}_amd64.deb"
        dest: /tmp/balena.deb
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Install balena
      become: true
      apt:
          deb: /tmp/balena.deb
          state: present
          update_cache: true
