---
- name: Install broot
  hosts: all
  gather_facts: False
  tags: broot
  tasks:
    - name: Download broot
      get_url:
        url: https://dystroy.org/broot/download/x86_64-linux/broot
        dest: /tmp/broot
        mode: 0700
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Copy broot to /usr/local/bin
      become: true
      copy:
        src: /tmp/broot
        dest: /usr/local/bin/broot
        mode: 0700
