---
- name: Install firejail
  hosts: all
  gather_facts: False
  tags: various,firejail
  tasks:
    - name: Download latest release metadata
      uri:
        timeout: 30
        url: https://api.github.com/repos/netblue30/firejail/releases/latest
        return_content: yes
      register: firejail_latest_version_metadata
      until: firejail_latest_version_metadata is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Parse latest version tag
      set_fact:
        firejail_latest_version: "{{ firejail_latest_version_metadata.json.tag_name }}"
    - name: Download firejail {{ firejail_latest_version }}
      get_url:
        url: "https://github.com/netblue30/firejail/releases/download/{{ firejail_latest_version }}/firejail_{{ firejail_latest_version }}_1_amd64.deb"
        dest: "/tmp/firejail_{{ firejail_latest_version }}_1_amd64.deb"
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Install firejail
      become: true
      apt:
        deb: "/tmp/firejail_{{ firejail_latest_version }}_1_amd64.deb"
