---
- name: Install 'lsd', a better 'ls'
  hosts: all
  gather_facts: False
  tags: lsd
  tasks:
    - name: Download latest release metadata
      uri:
        timeout: 30
        url: https://api.github.com/repos/lsd-rs/lsd/releases/latest
        return_content: yes
      register: lsd_latest_version_metadata
      until: lsd_latest_version_metadata is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Parse latest version tag
      set_fact:
        lsd_latest_version: "{{ lsd_latest_version_metadata.json.tag_name | regex_replace('^v', '') }}"
    - name: Download lsd {{ lsd_latest_version }}
      get_url:
        url: "https://github.com/lsd-rs/lsd/releases/download/v{{ lsd_latest_version }}/lsd-musl_{{ lsd_latest_version }}_amd64.deb"
        dest: "/tmp/lsd-musl_{{ lsd_latest_version }}_amd64.deb"
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Install lsd
      become: true
      apt:
        deb: "/tmp/lsd-musl_{{ lsd_latest_version }}_amd64.deb"
        state: present
