---
- name: Install mcfly for searching shell history
  hosts: all
  tasks:
    - name: Download mcfly install script
      get_url:
        url: https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh
        dest: /tmp/mcfly-install.sh
        mode: 0700
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Store md5sum of current binary
      shell:
        cmd: md5sum /usr/local/bin/mcfly | awk '{print $1}'
      register: current_md5sum
      changed_when: false
    - name: Install mcfly to default /usr/local/bin
      shell: /tmp/mcfly-install.sh --force --git cantino/mcfly
      become: true
      args:
        executable: /bin/sh
      changed_when: false
    - name: Report as changed when new mcfly version installed
      shell:
        cmd: md5sum /usr/local/bin/mcfly | awk '{print $1}'
      register: new_md5sum
      changed_when: current_md5sum.stdout != new_md5sum.stdout
