---
- name: Install viddy
  hosts: all
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/sachaos/viddy/releases/latest
        return_content: yes
      register: viddy_latest_version_metadata
      until: viddy_latest_version_metadata is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Parse latest version tag
      set_fact:
        viddy_latest_version: "{{ viddy_latest_version_metadata.json.tag_name | regex_replace('^v', '') }}"
    - name: Download viddy
      get_url:
        url: "https://github.com/sachaos/viddy/releases/latest/download/viddy_{{ viddy_latest_version }}_Linux_x86_64.tar.gz"
        dest: /tmp/viddy.tar.gz
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Unpack viddy
      unarchive:
        src: /tmp/viddy.tar.gz
        dest: /tmp
        remote_src: yes
    - name: Move viddy to /usr/local/bin
      become: true
      shell: mv /tmp/viddy /usr/local/bin/viddy
    - name: Make viddy executable
      file:
        path: /usr/local/bin/viddy
        mode: 0700
