---
- name: Install viddy
  hosts: all
  gather_facts: False
  tags: viddy
  tasks:
    - name: Download latest release metadata
      uri:
        url: https://api.github.com/repos/sachaos/viddy/releases/latest
        return_content: yes
      register: viddy_latest_version_metadata
      until: viddy_latest_version_metadata is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Parse latest version tag
      set_fact:
        viddy_latest_version: "{{ viddy_latest_version_metadata.json.tag_name | regex_replace('^v', '') }}"
    - name: Download viddy {{ viddy_latest_version }}
      get_url:
        url: "https://github.com/sachaos/viddy/releases/download/v{{ viddy_latest_version }}/viddy_Linux_x86_64.tar.gz"
        dest: /tmp/viddy.tar.gz
      register: download
      until: download is success
      retries: 3
      delay: 5
      changed_when: false
    - name: Remove temp binary if present
      file:
        path: /tmp/viddy
        state: absent
      changed_when: false
    - name: Unpack viddy
      unarchive:
        src: /tmp/viddy.tar.gz
        dest: /tmp
        remote_src: yes
      changed_when: false
    - name: Store md5sum of current binary
      shell:
        cmd: md5sum /usr/local/bin/viddy | awk '{print $1}'
      register: current_md5sum
      changed_when: false
    - name: Store md5sum of new binary
      shell:
        cmd: md5sum /tmp/viddy | awk '{print $1}'
      register: new_md5sum
      changed_when: false
    - name: Exit if no update is available
      meta: end_play
      when: current_md5sum.stdout == new_md5sum.stdout
    - name: Move viddy to /usr/local/bin
      become: true
      shell: mv /tmp/viddy /usr/local/bin/viddy
    - name: Make viddy executable
      file:
        path: /usr/local/bin/viddy
        mode: 0700
