---
- name: Install zoom from official site
  hosts: all
  tasks:
    - name: Download zoom deb package
      get_url:
        url: https://zoom.us/client/latest/zoom_amd64.deb
        dest: /tmp/zoom_amd64.deb
        mode: 0700
        timeout: 30
      register: download
      until: download is success
      retries: 3
      delay: 5
    - name: Install zoom
      become: true
      apt:
        deb: /tmp/zoom_amd64.deb
        state: present
        update_cache: true
